#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  does_this_work:
    secure: KrPaYlWG24jiYCGe8W+cxRoKvZ6beStfan5k2gALLs0iXRYREYScEKN11xavKKNbtXbEmuPTQunQWoLGlxeDiRACdetF7XQHiyTbs/r5nAc=
  id_rsa_deploy:
    secure: q9847HMo4TdFMMAQylzY5u1NAXUmGmCECWogwNyj8lXINcl3471eMia5HePSacbRoB32+gd6LPxlhhAs8xUn8wpCRlR8DtXl75w6/EIImtgPLsJAyutlZSHSJvldRNajPrzfuAkM7WPPO9/baOIneqz10pe2G4g/LibceXdUnnYQeECAox/dECiisodkF2QNmO6E6fU6Ir29D1rpJLkYFWrhZ+ue/Il4VMimoIQ1EXwH/IfP7jE9kTCe/UZTwJCWZ3C/1cC9V//2scmRLtdN0UkBWWsDCtxJdMFRfauUKlu7UIPDrxExJkqKQp03p+MFUP50jIMaz1ESMYlvF2cqKn5jVyqNWlgZUtg903ATQLLCR40hdCu/JNbogixZfFdU7aySriTuQO+hkXDZQwalZ53uq8M16hcDYSqAXJ7P8G+6sq4eJCkMzhoyDDt8zofbS3YfcvNTVbl02Z28eYZc4f3whNYnrNFvgwx4IKG/NgYZQ1dneFmAB4CFE+r7k5QewqOOubN5BubjEJ0UooOSpRRzBT/6QgBAl9DWuX9VKduJf04x6139FQEHJBIulh65Xd6Nnk7wSmRZmQZ8ra7X4ugg1ee1ms6KGw+VyDeJl+mKH2TlF6+Ue8YZ3gR4klkRk+t0RZ1v94ttGi+gQUfT+og/5/7Lzg57P5Pqx2a0JXgGnF+GKtgBxQoyB9nLpZAcB3fk1VCST7sQberkbpweWpi0QezqlH6L7SGCrK5rKNsUvgtL4UD/hM2o9TNGtWK7Fv1fI1DXL9bdCsoF3kxSIuMlMe50voAw48w5gwjJ0apaOhLpSdPibu44HTs37ILLPKjJ6v4axDE5L15JWNwa/5ULUrhO1B5RsL4ffGtFCSmbOfxf31TLEmv5BWVFixunqz6EHNOU4ZRuw/iPdUDJtyerj7xYrYoWrn55Lg7f1NnDt7cxU7PvWy7DSsGOgzxHgwAUu23ywHSIHHFJIjJsap7byB8qm+97UYdN8h3k10X4PrLUWBENkUIV2RMEu3bi7oywGfizV1Ns3yKQEVfpdZLjNKC/fPFUwhuHaEHvCSpcGTm4L70m29ETud1YeUpdq0pVXb56DOM8CdeQ2DtqqSj+/5+zGu8vwSRtjxAKFvn9whm0hwZvtlyKJ5OJ364yTlkFlJHUf9aN/GNzrYc18lHjX9oQkZ2xccRJGpSi7QBW8MAHjkSCN4V6d1kGSOeAVXBh1oiKz867xT22BrZMdWuUeZmPkIyRyRbtGjBgL1rl+XUgclNxh3uVjQGUi5ETtvRG/vswfBaZfKVWTTpCutKQhpCP3BkIXnssEAg7Sc/U8fSEpoA4VOWJf3ocwRXV+lwairvYhuOsLXR03wqzI4YWppsMTZnVWWa/uqRKMg5tloDjsjyKDl71tNLQY/CnZDdzS1J9ezFfLYsj6gWvIuiE2mGp049U4YsyVd8/+mlcjJfsZf/RYKwwjPjk1hv2ir+UUqUIxb3jVJR06wAsRFykUg3rA0/6lQXTA/OM95KXbRJu2iX4Ma5bzB6VcHcoTVLewU3pJ+cXLpbayH1Cgmk+IilYJ8N587l4eHPENUT/5c1SNEn1yHan6SJEtmLV6RQv03JQULM8nsND6Ak7tQygCm1dPg7XNouwEvtYWKEO09b6fC3NRik0Mo/+lRGB/cb+QHWOTqpLGWmKDXjax0yJb+JKFWKThLWIcS1wEQ4Duxp8fohmuWfiWa0Yv8uzBPYnuswdgtzP3VOGY3rOflqP11Mku6IlSGh5RxUTp6xoitn27KHoc754cppKYyHi2M14+s3CJkN0VMBT1Tk0xX4tyZXKQ4W6pSDbXNQY0b9B+rxmHPBfnQeqKNSZmlK1HGO0kgYnjXm2t/eHRNWdtsgaNHNRae2QKIAI6p3Qca0UjUP9NNbi5DsIwFgIy/MW5cq6oa9WYwW3ulldRnVHe5W/khtOGmj8gYaWKKBfv0HJII9G+ghRZ3nHOBxQokegXHkWrOlGLmyfdTUoRWkzDPfi6FbY8yQAswqreTX3LXFTp1f5LDg20yo8DE6FTGzq0mPgbYSgHjP2jE+rTLnrtFyXBDLncgyDi7vkZGOp4qkeBDujTjfF7nNQM4MFVKJB4rLu0/6s+jRGZiBbvHPH3C071g7dBXiHvLJmV+CyogHbOpPgdDaHe+PjvHwB/5i7O+2xII4EnXfubX1vDjvEJSoWx8yR1ZuF+p0Jk540ZjedVjuNhhJhefb12i862B4l
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build
  - go deploy Release
  - echo.

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off
