#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

#environment variables
environment:
  gh_token:
    secure: Nww9ToyuLy9Dam9uQ/gp60uD2fMNrdVyZ9zzAfgtOubVCItC2xcWMtvwaZQ8bRDF

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd ./build
  - go deploy Release
  - echo 'Build (and Deploy) completed...'

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off
